<div class="space-y-6">
    <div class="flex items-center gap-2 text-sm text-zinc-500">
        <a href="{{ route('dashboard') }}" wire:navigate class="hover:text-zinc-900">Issues</a>
        <svg class="size-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 0 1 .02-1.06L11.168 10 7.23 6.29a.75.75 0 1 1 1.04-1.08l4.5 4.25a.75.75 0 0 1 0 1.08l-4.5 4.25a.75.75 0 0 1-1.06-.02z" clip-rule="evenodd"/></svg>
        <code class="font-mono font-medium text-zinc-700">{{ $issue->reference }}</code>
    </div>

    <div class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-xs">
        <div class="flex flex-wrap items-start justify-between gap-4">
            <div class="flex-1 min-w-0">
                <div class="flex flex-wrap items-center gap-3">
                    <code class="font-mono text-sm font-semibold text-zinc-500">{{ $issue->reference }}</code>
                    <h1 class="text-xl font-semibold tracking-tight text-zinc-900">{{ $issue->title }}</h1>
                    <x-status-pill :status="$issue->status" />
                    <span class="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold ring-1 ring-inset {{ $issue->priority->classes() }}">
                        <span class="size-1.5 rounded-full {{ $issue->priority->dot() }}"></span>{{ $issue->priority->label() }}
                    </span>
                    @if ($issue->label)
                        <span class="rounded bg-zinc-100 px-2 py-0.5 text-[11px] font-medium text-zinc-700">{{ $issue->label }}</span>
                    @endif
                </div>
                @if ($issue->description)
                    <p class="mt-3 max-w-2xl text-sm text-zinc-600">{{ $issue->description }}</p>
                @endif
                <dl class="mt-5 grid grid-cols-2 gap-x-8 gap-y-3 sm:grid-cols-4">
                    <div>
                        <dt class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Reporter</dt>
                        <dd class="mt-1 flex items-center gap-2 text-sm text-zinc-900">
                            <span class="grid size-6 place-items-center rounded-full bg-zinc-200 text-[10px] font-semibold text-zinc-700">{{ $issue->reporter->initials() }}</span>
                            {{ $issue->reporter->name }}
                        </dd>
                    </div>
                    <div>
                        <dt class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Assignee</dt>
                        <dd class="mt-1 flex items-center gap-2 text-sm text-zinc-900">
                            @if ($issue->assignee)
                                <span class="grid size-6 place-items-center rounded-full bg-zinc-200 text-[10px] font-semibold text-zinc-700">{{ $issue->assignee->initials() }}</span>
                                {{ $issue->assignee->name }}
                            @else
                                <span class="text-zinc-400">Unassigned</span>
                            @endif
                        </dd>
                    </div>
                    <div>
                        <dt class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Started</dt>
                        <dd class="mt-1 text-sm text-zinc-900">{{ optional($issue->started_at)->diffForHumans() ?? '—' }}</dd>
                    </div>
                    <div>
                        <dt class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Closed</dt>
                        <dd class="mt-1 text-sm text-zinc-900">{{ optional($issue->closed_at)->diffForHumans() ?? '—' }}</dd>
                    </div>
                </dl>
            </div>
            <div class="rounded-lg bg-zinc-50 px-3 py-2 text-right">
                <div class="text-[11px] font-semibold uppercase tracking-wider text-zinc-500">Active places</div>
                <div class="mt-1 flex flex-wrap justify-end gap-1">
                    @forelse ($activePlaces as $place)
                        <code class="rounded bg-white px-1.5 py-0.5 font-mono text-[11px] text-zinc-700 ring-1 ring-zinc-200">{{ $place }}</code>
                    @empty
                        <span class="text-xs text-zinc-400">none</span>
                    @endforelse
                </div>
            </div>
        </div>
    </div>

    {{-- Workflow diagram (full-width, prominent) --}}
    <div class="rounded-2xl border border-zinc-200 bg-white shadow-xs">
        <div class="flex items-center justify-between border-b border-zinc-100 px-6 py-4">
            <div>
                <h2 class="text-sm font-semibold tracking-tight text-zinc-900">Workflow diagram</h2>
                <p class="mt-0.5 text-xs text-zinc-500">Active places highlighted live. Generated by <code class="font-mono">MermaidExporter</code> + <code class="font-mono">classDef</code>.</p>
            </div>
            <a href="https://symflowbuilder.com/editor/cmomkgau10001lcqgop3pd0f3" target="_blank" rel="noopener"
               class="inline-flex items-center gap-1.5 rounded-md border border-zinc-200 bg-white px-2.5 py-1 text-[11px] font-medium text-zinc-600 transition hover:border-indigo-300 hover:text-indigo-700">
                View on symflowbuilder.com
                <svg class="size-3" viewBox="0 0 20 20" fill="currentColor"><path d="M11 3a1 1 0 1 0 0 2h2.586L7.293 11.293a1 1 0 1 0 1.414 1.414L15 6.414V9a1 1 0 1 0 2 0V4a1 1 0 0 0-1-1h-5z"/><path d="M5 5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-3a1 1 0 1 0-2 0v3H5V7h3a1 1 0 1 0 0-2H5z"/></svg>
            </a>
        </div>
        <div class="p-4">
            <div class="min-h-[280px]">
                <livewire:components.workflow-diagram
                    workflow-name="issue_tracking"
                    :active-places="$activePlaces"
                    :key="'diagram-'.$issue->id.'-'.implode('-', $activePlaces)" />
            </div>
        </div>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <div class="space-y-6 lg:col-span-2">
            <div class="rounded-2xl border border-zinc-200 bg-white shadow-xs">
                <div class="border-b border-zinc-100 px-6 py-4">
                    <h2 class="text-sm font-semibold tracking-tight text-zinc-900">Workflow actions</h2>
                    <p class="mt-0.5 text-xs text-zinc-500">
                        @if ($currentUser)
                            Acting as <span class="font-medium text-zinc-700">{{ $currentUser->name }}</span> ({{ $currentUser->role->label() }}).
                        @else
                            Sign in via the top-right to fire role-guarded transitions.
                        @endif
                    </p>
                </div>

                @if (! $currentUser)
                    <div class="border-b border-zinc-100 bg-amber-50/60 px-6 py-3 text-sm text-amber-800">
                        <strong class="font-semibold">Not signed in.</strong> Most actions require a role. Use the "Sign in to demo" button in the top-right.
                    </div>
                @endif

                <div class="space-y-5 p-6">
                    <div>
                        <label class="block text-xs font-semibold uppercase tracking-wider text-zinc-500">Comment / reason (optional)</label>
                        <textarea wire:model="reason" rows="2" placeholder="Captured in the audit log alongside the transition…"
                                  class="mt-1 w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm shadow-xs placeholder:text-zinc-400 focus:border-indigo-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/20"></textarea>
                    </div>

                    @if (count($grouped['available']) > 0)
                        <section>
                            <div class="mb-2 flex items-center gap-2">
                                <span class="size-2 rounded-full bg-emerald-500"></span>
                                <h3 class="text-xs font-semibold uppercase tracking-wider text-emerald-700">Available now</h3>
                            </div>
                            <div class="grid gap-2 sm:grid-cols-2">
                                @foreach ($grouped['available'] as $row)
                                    @php
                                        $btn = match ($row['intent']) {
                                            'primary' => 'bg-indigo-600 text-white hover:bg-indigo-700',
                                            'destructive' => 'bg-rose-600 text-white hover:bg-rose-700',
                                            'success' => 'bg-emerald-600 text-white hover:bg-emerald-700',
                                            default => 'bg-zinc-900 text-white hover:bg-zinc-800',
                                        };
                                    @endphp
                                    <button type="button"
                                            wire:click="fire('{{ $row['transition']->name }}')"
                                            class="group flex flex-col items-start gap-1 rounded-lg px-4 py-3 text-left text-sm font-semibold transition {{ $btn }}">
                                        <span class="flex items-center gap-2">
                                            {{ $row['transition']->name }}
                                            @if ($row['transition']->guard)
                                                <span class="rounded bg-white/20 px-1.5 py-0.5 font-mono text-[10px]">{{ $row['transition']->guard }}</span>
                                            @endif
                                        </span>
                                        <span class="text-[11px] font-normal opacity-80">
                                            {{ implode(', ', $row['transition']->froms) }} → {{ implode(', ', $row['transition']->tos) }}
                                        </span>
                                    </button>
                                @endforeach
                            </div>
                        </section>
                    @endif

                    @if (count($grouped['awaiting']) > 0)
                        <section>
                            <div class="mb-2 flex items-center gap-2">
                                <span class="size-2 rounded-full bg-amber-500"></span>
                                <h3 class="text-xs font-semibold uppercase tracking-wider text-amber-700">Awaiting another actor</h3>
                            </div>
                            <ul class="grid gap-2 sm:grid-cols-2">
                                @foreach ($grouped['awaiting'] as $row)
                                    <li class="flex flex-col gap-1 rounded-lg border border-amber-200 bg-amber-50/60 px-4 py-3 text-left">
                                        <div class="flex items-center gap-2 text-sm font-semibold text-amber-900">
                                            {{ $row['transition']->name }}
                                            @if ($row['transition']->guard)
                                                <span class="rounded bg-white/70 px-1.5 py-0.5 font-mono text-[10px] text-amber-800">{{ $row['transition']->guard }}</span>
                                            @endif
                                        </div>
                                        <span class="text-[11px] text-amber-800/80">
                                            {{ implode(', ', $row['transition']->froms) }} → {{ implode(', ', $row['transition']->tos) }}
                                        </span>
                                        <span class="text-[11px] font-medium text-amber-900">{{ $row['reason'] }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </section>
                    @endif

                    @if (count($grouped['inactive']) > 0)
                        <section x-data="{ open: false }">
                            <button type="button" @click="open = !open"
                                    class="flex w-full items-center justify-between gap-2 rounded-md px-2 py-1 text-left">
                                <span class="flex items-center gap-2">
                                    <span class="size-2 rounded-full bg-zinc-300"></span>
                                    <span class="text-xs font-semibold uppercase tracking-wider text-zinc-500">Not in this state ({{ count($grouped['inactive']) }})</span>
                                </span>
                                <svg class="size-4 text-zinc-400 transition" :class="{ 'rotate-180': open }" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 0 1 1.06.02L10 11.06l3.71-3.83a.75.75 0 1 1 1.08 1.04l-4.25 4.39a.75.75 0 0 1-1.08 0L5.21 8.27a.75.75 0 0 1 .02-1.06z" clip-rule="evenodd"/></svg>
                            </button>
                            <ul x-show="open" x-cloak x-transition class="mt-2 grid gap-1 text-[11px] text-zinc-500 sm:grid-cols-2">
                                @foreach ($grouped['inactive'] as $row)
                                    <li class="rounded-md bg-zinc-50 px-3 py-2">
                                        <code class="font-mono font-semibold text-zinc-700">{{ $row['transition']->name }}</code>
                                        <span class="ml-1">— {{ $row['reason'] }}</span>
                                    </li>
                                @endforeach
                            </ul>
                        </section>
                    @endif
                </div>
            </div>

            <div class="rounded-2xl border border-zinc-200 bg-white shadow-xs">
                <div class="border-b border-zinc-100 px-6 py-4">
                    <h2 class="text-sm font-semibold tracking-tight text-zinc-900">Activity timeline</h2>
                    <p class="mt-0.5 text-xs text-zinc-500">Captured by the <code class="font-mono">AuditLogMiddleware</code>.</p>
                </div>
                <ul class="divide-y divide-zinc-100">
                    @forelse ($issue->auditLogs as $log)
                        <li class="flex gap-4 px-6 py-4">
                            <div class="flex-none pt-1">
                                <span class="grid size-8 place-items-center rounded-full bg-zinc-100 text-[11px] font-semibold text-zinc-700">{{ $log->actor?->initials() ?? '··' }}</span>
                            </div>
                            <div class="min-w-0 flex-1">
                                <div class="flex flex-wrap items-baseline gap-x-2">
                                    <span class="text-sm font-semibold text-zinc-900">{{ $log->actor?->name ?? 'System' }}</span>
                                    <span class="text-xs text-zinc-500">fired</span>
                                    <code class="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-[11px] text-zinc-800">{{ $log->transition }}</code>
                                    <span class="ml-auto text-xs text-zinc-400">{{ $log->occurred_at->diffForHumans() }}</span>
                                </div>
                                <div class="mt-1 flex flex-wrap items-center gap-1 text-[11px] text-zinc-500">
                                    @foreach ((array) $log->marking_before as $p)
                                        <code class="rounded bg-zinc-50 px-1 py-0.5 font-mono text-zinc-500 ring-1 ring-zinc-200">{{ $p }}</code>
                                    @endforeach
                                    <svg class="size-3 text-zinc-400" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 0 1 .02-1.06L11.168 10 7.23 6.29a.75.75 0 1 1 1.04-1.08l4.5 4.25a.75.75 0 0 1 0 1.08l-4.5 4.25a.75.75 0 0 1-1.06-.02z" clip-rule="evenodd"/></svg>
                                    @foreach ((array) $log->marking_after as $p)
                                        <code class="rounded bg-indigo-50 px-1 py-0.5 font-mono text-indigo-700 ring-1 ring-indigo-200">{{ $p }}</code>
                                    @endforeach
                                </div>
                                @if ($log->reason)
                                    <p class="mt-2 rounded-md bg-zinc-50 px-3 py-2 text-sm italic text-zinc-700">"{{ $log->reason }}"</p>
                                @endif
                            </div>
                        </li>
                    @empty
                        <li class="px-6 py-12 text-center text-sm text-zinc-500">No activity yet.</li>
                    @endforelse
                </ul>
            </div>
        </div>

        <div class="space-y-6">
            <div class="rounded-2xl border border-zinc-200 bg-white shadow-xs">
                <div class="border-b border-zinc-100 px-6 py-4">
                    <h2 class="text-sm font-semibold tracking-tight text-zinc-900">Marking</h2>
                    <p class="mt-0.5 text-xs text-zinc-500">Petri-net token count per place.</p>
                </div>
                <div class="p-4">
                    @php $marking = $issue->getWorkflowMarking()->toArray(); @endphp
                    <ul class="grid grid-cols-2 gap-2 text-xs">
                        @foreach ($marking as $place => $tokens)
                            <li class="flex items-center justify-between rounded-md px-2 py-1 {{ $tokens > 0 ? 'bg-indigo-50 text-indigo-800 ring-1 ring-indigo-200' : 'text-zinc-500' }}">
                                <code class="font-mono">{{ $place }}</code>
                                <span class="font-semibold">{{ $tokens }}</span>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>

            <div class="rounded-2xl border border-zinc-200 bg-white p-4 shadow-xs">
                <h2 class="text-sm font-semibold tracking-tight text-zinc-900">View on symflowbuilder.com</h2>
                <p class="mt-1 text-xs text-zinc-500">Inspect the canonical canvas at <a href="https://symflowbuilder.com/editor/cmomkgau10001lcqgop3pd0f3" target="_blank" rel="noopener" class="font-medium text-indigo-700 hover:underline">symflowbuilder.com</a> — sign in there to fork and edit your own copy.</p>
            </div>
        </div>
    </div>
</div>
